<?php

namespace Edgcarmu\Crgeodata\database\seeds;

use Edgcarmu\Crgeodata\app\Models\Distrito;
use Illuminate\Database\Seeder;

class GeoDataCrDistritosTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Distrito::updateOrCreate(['distrito_id' => 10101, 'canton_id' => 101, 'tax_id' => 1, 'name' => 'Carmen']);
        Distrito::updateOrCreate(['distrito_id' => 10102, 'canton_id' => 101, 'tax_id' => 2, 'name' => 'Merced']);
        Distrito::updateOrCreate(['distrito_id' => 10103, 'canton_id' => 101, 'tax_id' => 3, 'name' => 'Hospital']);
        Distrito::updateOrCreate(['distrito_id' => 10104, 'canton_id' => 101, 'tax_id' => 4, 'name' => 'Catedral']);
        Distrito::updateOrCreate(['distrito_id' => 10105, 'canton_id' => 101, 'tax_id' => 5, 'name' => 'Zapote']);
        Distrito::updateOrCreate(['distrito_id' => 10106, 'canton_id' => 101, 'tax_id' => 6, 'name' => 'San Francisco de Dos Ríos']);
        Distrito::updateOrCreate(['distrito_id' => 10107, 'canton_id' => 101, 'tax_id' => 7, 'name' => 'Uruca']);
        Distrito::updateOrCreate(['distrito_id' => 10108, 'canton_id' => 101, 'tax_id' => 8, 'name' => 'Mata Redonda']);
        Distrito::updateOrCreate(['distrito_id' => 10109, 'canton_id' => 101, 'tax_id' => 9, 'name' => 'Pavas']);
        Distrito::updateOrCreate(['distrito_id' => 10110, 'canton_id' => 101, 'tax_id' => 10, 'name' => 'Hatillo']);
        Distrito::updateOrCreate(['distrito_id' => 10111, 'canton_id' => 101, 'tax_id' => 11, 'name' => 'San Sebástian']);
        Distrito::updateOrCreate(['distrito_id' => 10201, 'canton_id' => 102, 'tax_id' => 1, 'name' => 'Escazú']);
        Distrito::updateOrCreate(['distrito_id' => 10202, 'canton_id' => 102, 'tax_id' => 2, 'name' => 'San Antonio']);
        Distrito::updateOrCreate(['distrito_id' => 10203, 'canton_id' => 102, 'tax_id' => 3, 'name' => 'San Rafael']);
        Distrito::updateOrCreate(['distrito_id' => 10301, 'canton_id' => 103, 'tax_id' => 1, 'name' => 'Desamparados']);
        Distrito::updateOrCreate(['distrito_id' => 10302, 'canton_id' => 103, 'tax_id' => 2, 'name' => 'San Miguel']);
        Distrito::updateOrCreate(['distrito_id' => 10303, 'canton_id' => 103, 'tax_id' => 3, 'name' => 'San Juan de Dios']);
        Distrito::updateOrCreate(['distrito_id' => 10304, 'canton_id' => 103, 'tax_id' => 4, 'name' => 'San Rafaél Arriba']);
        Distrito::updateOrCreate(['distrito_id' => 10305, 'canton_id' => 103, 'tax_id' => 5, 'name' => 'San Antonio']);
        Distrito::updateOrCreate(['distrito_id' => 10306, 'canton_id' => 103, 'tax_id' => 6, 'name' => 'Frailes']);
        Distrito::updateOrCreate(['distrito_id' => 10307, 'canton_id' => 103, 'tax_id' => 7, 'name' => 'Patarra']);
        Distrito::updateOrCreate(['distrito_id' => 10308, 'canton_id' => 103, 'tax_id' => 8, 'name' => 'San Cristóbal']);
        Distrito::updateOrCreate(['distrito_id' => 10309, 'canton_id' => 103, 'tax_id' => 9, 'name' => 'Rosario']);
        Distrito::updateOrCreate(['distrito_id' => 10310, 'canton_id' => 103, 'tax_id' => 10, 'name' => 'Damas']);
        Distrito::updateOrCreate(['distrito_id' => 10311, 'canton_id' => 103, 'tax_id' => 11, 'name' => 'San Rafaél Abajo']);
        Distrito::updateOrCreate(['distrito_id' => 10312, 'canton_id' => 103, 'tax_id' => 12, 'name' => 'Gravilias']);
        Distrito::updateOrCreate(['distrito_id' => 10313, 'canton_id' => 103, 'tax_id' => 13, 'name' => 'Los Guido']);
        Distrito::updateOrCreate(['distrito_id' => 10401, 'canton_id' => 104, 'tax_id' => 1, 'name' => 'Santiago']);
        Distrito::updateOrCreate(['distrito_id' => 10402, 'canton_id' => 104, 'tax_id' => 2, 'name' => 'Mercedes Sur']);
        Distrito::updateOrCreate(['distrito_id' => 10403, 'canton_id' => 104, 'tax_id' => 3, 'name' => 'Barbacoas']);
        Distrito::updateOrCreate(['distrito_id' => 10404, 'canton_id' => 104, 'tax_id' => 4, 'name' => 'Grifo Alto']);
        Distrito::updateOrCreate(['distrito_id' => 10405, 'canton_id' => 104, 'tax_id' => 5, 'name' => 'San Rafaél']);
        Distrito::updateOrCreate(['distrito_id' => 10406, 'canton_id' => 104, 'tax_id' => 6, 'name' => 'Candelarita']);
        Distrito::updateOrCreate(['distrito_id' => 10407, 'canton_id' => 104, 'tax_id' => 7, 'name' => 'Desamparaditos']);
        Distrito::updateOrCreate(['distrito_id' => 10408, 'canton_id' => 104, 'tax_id' => 8, 'name' => 'San Antonio']);
        Distrito::updateOrCreate(['distrito_id' => 10409, 'canton_id' => 104, 'tax_id' => 9, 'name' => 'Chires']);
        Distrito::updateOrCreate(['distrito_id' => 10501, 'canton_id' => 105, 'tax_id' => 1, 'name' => 'San Marcos']);
        Distrito::updateOrCreate(['distrito_id' => 10502, 'canton_id' => 105, 'tax_id' => 2, 'name' => 'San Lorenzo']);
        Distrito::updateOrCreate(['distrito_id' => 10503, 'canton_id' => 105, 'tax_id' => 3, 'name' => 'San Carlos']);
        Distrito::updateOrCreate(['distrito_id' => 10601, 'canton_id' => 106, 'tax_id' => 1, 'name' => 'Aserrí']);
        Distrito::updateOrCreate(['distrito_id' => 10602, 'canton_id' => 106, 'tax_id' => 2, 'name' => 'Tarbaca']);
        Distrito::updateOrCreate(['distrito_id' => 10603, 'canton_id' => 106, 'tax_id' => 3, 'name' => 'Vuelta del Jorco']);
        Distrito::updateOrCreate(['distrito_id' => 10604, 'canton_id' => 106, 'tax_id' => 4, 'name' => 'San Gabriel']);
        Distrito::updateOrCreate(['distrito_id' => 10605, 'canton_id' => 106, 'tax_id' => 5, 'name' => 'Legua']);
        Distrito::updateOrCreate(['distrito_id' => 10606, 'canton_id' => 106, 'tax_id' => 6, 'name' => 'Monterrey']);
        Distrito::updateOrCreate(['distrito_id' => 10607, 'canton_id' => 106, 'tax_id' => 7, 'name' => 'Salitrillos']);
        Distrito::updateOrCreate(['distrito_id' => 10701, 'canton_id' => 107, 'tax_id' => 1, 'name' => 'Mora']);
        Distrito::updateOrCreate(['distrito_id' => 10702, 'canton_id' => 107, 'tax_id' => 2, 'name' => 'Guayabo']);
        Distrito::updateOrCreate(['distrito_id' => 10703, 'canton_id' => 107, 'tax_id' => 3, 'name' => 'Tabarcia']);
        Distrito::updateOrCreate(['distrito_id' => 10704, 'canton_id' => 107, 'tax_id' => 4, 'name' => 'Piedras Negras']);
        Distrito::updateOrCreate(['distrito_id' => 10705, 'canton_id' => 107, 'tax_id' => 5, 'name' => 'Picagres']);
        Distrito::updateOrCreate(['distrito_id' => 10706, 'canton_id' => 107, 'tax_id' => 6, 'name' => 'Jaris']);
        Distrito::updateOrCreate(['distrito_id' => 10707, 'canton_id' => 107, 'tax_id' => 7, 'name' => 'Quitirrisi']);
        Distrito::updateOrCreate(['distrito_id' => 10801, 'canton_id' => 108, 'tax_id' => 1, 'name' => 'Guadalupe']);
        Distrito::updateOrCreate(['distrito_id' => 10802, 'canton_id' => 108, 'tax_id' => 2, 'name' => 'San Francisco']);
        Distrito::updateOrCreate(['distrito_id' => 10803, 'canton_id' => 108, 'tax_id' => 3, 'name' => 'Calle Blancos']);
        Distrito::updateOrCreate(['distrito_id' => 10804, 'canton_id' => 108, 'tax_id' => 4, 'name' => 'Mata de Platano']);
        Distrito::updateOrCreate(['distrito_id' => 10805, 'canton_id' => 108, 'tax_id' => 5, 'name' => 'Ipis']);
        Distrito::updateOrCreate(['distrito_id' => 10806, 'canton_id' => 108, 'tax_id' => 6, 'name' => 'Rancho Redondo']);
        Distrito::updateOrCreate(['distrito_id' => 10807, 'canton_id' => 108, 'tax_id' => 7, 'name' => 'Purral']);
        Distrito::updateOrCreate(['distrito_id' => 10901, 'canton_id' => 109, 'tax_id' => 1, 'name' => 'Santa Ana']);
        Distrito::updateOrCreate(['distrito_id' => 10902, 'canton_id' => 109, 'tax_id' => 2, 'name' => 'Salitral']);
        Distrito::updateOrCreate(['distrito_id' => 10903, 'canton_id' => 109, 'tax_id' => 3, 'name' => 'Pozos']);
        Distrito::updateOrCreate(['distrito_id' => 10904, 'canton_id' => 109, 'tax_id' => 4, 'name' => 'Uruca']);
        Distrito::updateOrCreate(['distrito_id' => 10905, 'canton_id' => 109, 'tax_id' => 5, 'name' => 'Piedades']);
        Distrito::updateOrCreate(['distrito_id' => 10906, 'canton_id' => 109, 'tax_id' => 6, 'name' => 'Piedades']);
        Distrito::updateOrCreate(['distrito_id' => 11001, 'canton_id' => 110, 'tax_id' => 1, 'name' => 'Alajuelita']);
        Distrito::updateOrCreate(['distrito_id' => 11002, 'canton_id' => 110, 'tax_id' => 2, 'name' => 'San Josecito']);
        Distrito::updateOrCreate(['distrito_id' => 11003, 'canton_id' => 110, 'tax_id' => 3, 'name' => 'San Antonio']);
        Distrito::updateOrCreate(['distrito_id' => 11004, 'canton_id' => 110, 'tax_id' => 4, 'name' => 'Concepción']);
        Distrito::updateOrCreate(['distrito_id' => 11005, 'canton_id' => 110, 'tax_id' => 5, 'name' => 'San Felipe']);
        Distrito::updateOrCreate(['distrito_id' => 11101, 'canton_id' => 111, 'tax_id' => 1, 'name' => 'San Isidro']);
        Distrito::updateOrCreate(['distrito_id' => 11102, 'canton_id' => 111, 'tax_id' => 2, 'name' => 'San Rafaél']);
        Distrito::updateOrCreate(['distrito_id' => 11103, 'canton_id' => 111, 'tax_id' => 3, 'name' => 'Dulce Nombre de Jesús']);
        Distrito::updateOrCreate(['distrito_id' => 11104, 'canton_id' => 111, 'tax_id' => 4, 'name' => 'Patalillo']);
        Distrito::updateOrCreate(['distrito_id' => 11105, 'canton_id' => 111, 'tax_id' => 5, 'name' => 'Cascajal']);
        Distrito::updateOrCreate(['distrito_id' => 11201, 'canton_id' => 112, 'tax_id' => 1, 'name' => 'San Ignacio']);
        Distrito::updateOrCreate(['distrito_id' => 11202, 'canton_id' => 112, 'tax_id' => 2, 'name' => 'Guaitil']);
        Distrito::updateOrCreate(['distrito_id' => 11203, 'canton_id' => 112, 'tax_id' => 3, 'name' => 'Palmichal']);
        Distrito::updateOrCreate(['distrito_id' => 11204, 'canton_id' => 112, 'tax_id' => 4, 'name' => 'Cangrejal']);
        Distrito::updateOrCreate(['distrito_id' => 11205, 'canton_id' => 112, 'tax_id' => 5, 'name' => 'Sabanillas']);
        Distrito::updateOrCreate(['distrito_id' => 11301, 'canton_id' => 113, 'tax_id' => 1, 'name' => 'San Juan']);
        Distrito::updateOrCreate(['distrito_id' => 11302, 'canton_id' => 113, 'tax_id' => 2, 'name' => 'Cinco Esquinas']);
        Distrito::updateOrCreate(['distrito_id' => 11303, 'canton_id' => 113, 'tax_id' => 3, 'name' => 'Anselmo Llorente']);
        Distrito::updateOrCreate(['distrito_id' => 11304, 'canton_id' => 113, 'tax_id' => 4, 'name' => 'León XIII']);
        Distrito::updateOrCreate(['distrito_id' => 11305, 'canton_id' => 113, 'tax_id' => 5, 'name' => 'Colima']);
        Distrito::updateOrCreate(['distrito_id' => 11401, 'canton_id' => 114, 'tax_id' => 1, 'name' => 'San Vicente']);
        Distrito::updateOrCreate(['distrito_id' => 11402, 'canton_id' => 114, 'tax_id' => 2, 'name' => 'San Jerónimo']);
        Distrito::updateOrCreate(['distrito_id' => 11403, 'canton_id' => 114, 'tax_id' => 3, 'name' => 'Trinidad']);
        Distrito::updateOrCreate(['distrito_id' => 11501, 'canton_id' => 115, 'tax_id' => 1, 'name' => 'San Pedro']);
        Distrito::updateOrCreate(['distrito_id' => 11502, 'canton_id' => 115, 'tax_id' => 2, 'name' => 'Sabanilla']);
        Distrito::updateOrCreate(['distrito_id' => 11503, 'canton_id' => 115, 'tax_id' => 3, 'name' => 'Betania']);
        Distrito::updateOrCreate(['distrito_id' => 11504, 'canton_id' => 115, 'tax_id' => 4, 'name' => 'San Rafaél']);
        Distrito::updateOrCreate(['distrito_id' => 11601, 'canton_id' => 116, 'tax_id' => 1, 'name' => 'San Pablo']);
        Distrito::updateOrCreate(['distrito_id' => 11602, 'canton_id' => 116, 'tax_id' => 2, 'name' => 'San Pedro']);
        Distrito::updateOrCreate(['distrito_id' => 11603, 'canton_id' => 116, 'tax_id' => 3, 'name' => 'San Juan de Mata']);
        Distrito::updateOrCreate(['distrito_id' => 11604, 'canton_id' => 116, 'tax_id' => 4, 'name' => 'San Luis']);
        Distrito::updateOrCreate(['distrito_id' => 11605, 'canton_id' => 116, 'tax_id' => 5, 'name' => 'Carara']);
        Distrito::updateOrCreate(['distrito_id' => 11701, 'canton_id' => 117, 'tax_id' => 1, 'name' => 'Santa María']);
        Distrito::updateOrCreate(['distrito_id' => 11702, 'canton_id' => 117, 'tax_id' => 2, 'name' => 'Jardín']);
        Distrito::updateOrCreate(['distrito_id' => 11703, 'canton_id' => 117, 'tax_id' => 3, 'name' => 'Copey']);
        Distrito::updateOrCreate(['distrito_id' => 11801, 'canton_id' => 118, 'tax_id' => 1, 'name' => 'Curridabat']);
        Distrito::updateOrCreate(['distrito_id' => 11802, 'canton_id' => 118, 'tax_id' => 2, 'name' => 'Granadilla']);
        Distrito::updateOrCreate(['distrito_id' => 11803, 'canton_id' => 118, 'tax_id' => 3, 'name' => 'Sánchez']);
        Distrito::updateOrCreate(['distrito_id' => 11804, 'canton_id' => 118, 'tax_id' => 4, 'name' => 'Tirrases']);
        Distrito::updateOrCreate(['distrito_id' => 11901, 'canton_id' => 119, 'tax_id' => 1, 'name' => 'San Isidro de El General']);
        Distrito::updateOrCreate(['distrito_id' => 11902, 'canton_id' => 119, 'tax_id' => 2, 'name' => 'General']);
        Distrito::updateOrCreate(['distrito_id' => 11903, 'canton_id' => 119, 'tax_id' => 3, 'name' => 'Daniel Flores']);
        Distrito::updateOrCreate(['distrito_id' => 11904, 'canton_id' => 119, 'tax_id' => 4, 'name' => 'Rivas']);
        Distrito::updateOrCreate(['distrito_id' => 11905, 'canton_id' => 119, 'tax_id' => 5, 'name' => 'San Pedro']);
        Distrito::updateOrCreate(['distrito_id' => 11906, 'canton_id' => 119, 'tax_id' => 6, 'name' => 'Platanares']);
        Distrito::updateOrCreate(['distrito_id' => 11907, 'canton_id' => 119, 'tax_id' => 7, 'name' => 'Pejibaye']);
        Distrito::updateOrCreate(['distrito_id' => 11908, 'canton_id' => 119, 'tax_id' => 8, 'name' => 'Cajón']);
        Distrito::updateOrCreate(['distrito_id' => 11909, 'canton_id' => 119, 'tax_id' => 9, 'name' => 'Barú']);
        Distrito::updateOrCreate(['distrito_id' => 11910, 'canton_id' => 119, 'tax_id' => 10, 'name' => 'Río Nuevo']);
        Distrito::updateOrCreate(['distrito_id' => 11911, 'canton_id' => 119, 'tax_id' => 11, 'name' => 'Páramo']);
        Distrito::updateOrCreate(['distrito_id' => 11912, 'canton_id' => 119, 'tax_id' => 12, 'name' => 'La Amistad']);
        Distrito::updateOrCreate(['distrito_id' => 12001, 'canton_id' => 120, 'tax_id' => 1, 'name' => 'San Pablo']);
        Distrito::updateOrCreate(['distrito_id' => 12002, 'canton_id' => 120, 'tax_id' => 2, 'name' => 'San Andrés']);
        Distrito::updateOrCreate(['distrito_id' => 12003, 'canton_id' => 120, 'tax_id' => 3, 'name' => 'Llano Bonito']);
        Distrito::updateOrCreate(['distrito_id' => 12004, 'canton_id' => 120, 'tax_id' => 4, 'name' => 'San Isidro']);
        Distrito::updateOrCreate(['distrito_id' => 12005, 'canton_id' => 120, 'tax_id' => 5, 'name' => 'Santa Cruz']);
        Distrito::updateOrCreate(['distrito_id' => 12006, 'canton_id' => 120, 'tax_id' => 6, 'name' => 'San Antonio']);
        Distrito::updateOrCreate(['distrito_id' => 20101, 'canton_id' => 201, 'tax_id' => 1, 'name' => 'ALAJUELA']);
        Distrito::updateOrCreate(['distrito_id' => 20102, 'canton_id' => 201, 'tax_id' => 2, 'name' => 'SAN JOSE']);
        Distrito::updateOrCreate(['distrito_id' => 20103, 'canton_id' => 201, 'tax_id' => 3, 'name' => 'CARRIZAL']);
        Distrito::updateOrCreate(['distrito_id' => 20104, 'canton_id' => 201, 'tax_id' => 4, 'name' => 'SAN ANTONIO']);
        Distrito::updateOrCreate(['distrito_id' => 20105, 'canton_id' => 201, 'tax_id' => 5, 'name' => 'GUACIMA']);
        Distrito::updateOrCreate(['distrito_id' => 20106, 'canton_id' => 201, 'tax_id' => 6, 'name' => 'SAN ISIDRO']);
        Distrito::updateOrCreate(['distrito_id' => 20107, 'canton_id' => 201, 'tax_id' => 7, 'name' => 'SABANILLA']);
        Distrito::updateOrCreate(['distrito_id' => 20108, 'canton_id' => 201, 'tax_id' => 8, 'name' => 'SAN RAFAEL']);
        Distrito::updateOrCreate(['distrito_id' => 20109, 'canton_id' => 201, 'tax_id' => 9, 'name' => 'RIO SEGUNDO']);
        Distrito::updateOrCreate(['distrito_id' => 20110, 'canton_id' => 201, 'tax_id' => 10, 'name' => 'DESAMPARADOS']);
        Distrito::updateOrCreate(['distrito_id' => 20111, 'canton_id' => 201, 'tax_id' => 11, 'name' => 'TURRUCARES']);
        Distrito::updateOrCreate(['distrito_id' => 20112, 'canton_id' => 201, 'tax_id' => 12, 'name' => 'TAMBOR']);
        Distrito::updateOrCreate(['distrito_id' => 20113, 'canton_id' => 201, 'tax_id' => 13, 'name' => 'GARITA']);
        Distrito::updateOrCreate(['distrito_id' => 20114, 'canton_id' => 201, 'tax_id' => 14, 'name' => 'SAN MIGUEL DE SARAPIQUI']);
        Distrito::updateOrCreate(['distrito_id' => 20201, 'canton_id' => 202, 'tax_id' => 1, 'name' => 'SAN RAMON']);
        Distrito::updateOrCreate(['distrito_id' => 20202, 'canton_id' => 202, 'tax_id' => 2, 'name' => 'SANTIAGO']);
        Distrito::updateOrCreate(['distrito_id' => 20203, 'canton_id' => 202, 'tax_id' => 3, 'name' => 'SAN JUAN']);
        Distrito::updateOrCreate(['distrito_id' => 20204, 'canton_id' => 202, 'tax_id' => 4, 'name' => 'PIEDADES NORTE']);
        Distrito::updateOrCreate(['distrito_id' => 20205, 'canton_id' => 202, 'tax_id' => 5, 'name' => 'PIEDADES SUR']);
        Distrito::updateOrCreate(['distrito_id' => 20206, 'canton_id' => 202, 'tax_id' => 6, 'name' => 'SAN RAFAEL']);
        Distrito::updateOrCreate(['distrito_id' => 20207, 'canton_id' => 202, 'tax_id' => 7, 'name' => 'SAN ISIDRO']);
        Distrito::updateOrCreate(['distrito_id' => 20208, 'canton_id' => 202, 'tax_id' => 8, 'name' => 'ANGELES']);
        Distrito::updateOrCreate(['distrito_id' => 20209, 'canton_id' => 202, 'tax_id' => 9, 'name' => 'ALFARO']);
        Distrito::updateOrCreate(['distrito_id' => 20210, 'canton_id' => 202, 'tax_id' => 10, 'name' => 'VOLIO']);
        Distrito::updateOrCreate(['distrito_id' => 20211, 'canton_id' => 202, 'tax_id' => 11, 'name' => 'CONCEPCION']);
        Distrito::updateOrCreate(['distrito_id' => 20212, 'canton_id' => 202, 'tax_id' => 12, 'name' => 'ZAPOTAL']);
        Distrito::updateOrCreate(['distrito_id' => 20213, 'canton_id' => 202, 'tax_id' => 13, 'name' => 'SAN ISIDRO DE PEÑAS BLANCAS']);
        Distrito::updateOrCreate(['distrito_id' => 20214, 'canton_id' => 202, 'tax_id' => 14, 'name' => 'SAN LORENZO']);
        Distrito::updateOrCreate(['distrito_id' => 20301, 'canton_id' => 203, 'tax_id' => 1, 'name' => 'GRECIA']);
        Distrito::updateOrCreate(['distrito_id' => 20302, 'canton_id' => 203, 'tax_id' => 2, 'name' => 'SAN ISIDRO']);
        Distrito::updateOrCreate(['distrito_id' => 20303, 'canton_id' => 203, 'tax_id' => 3, 'name' => 'SAN JOSE']);
        Distrito::updateOrCreate(['distrito_id' => 20304, 'canton_id' => 203, 'tax_id' => 4, 'name' => 'SAN ROQUE']);
        Distrito::updateOrCreate(['distrito_id' => 20305, 'canton_id' => 203, 'tax_id' => 5, 'name' => 'TACARES']);
        Distrito::updateOrCreate(['distrito_id' => 20306, 'canton_id' => 203, 'tax_id' => 6, 'name' => 'PUENTE DE PIEDRA']);
        Distrito::updateOrCreate(['distrito_id' => 20307, 'canton_id' => 203, 'tax_id' => 7, 'name' => 'BOLIVAR']);
        Distrito::updateOrCreate(['distrito_id' => 20401, 'canton_id' => 204, 'tax_id' => 1, 'name' => 'SAN MATEO']);
        Distrito::updateOrCreate(['distrito_id' => 20402, 'canton_id' => 204, 'tax_id' => 2, 'name' => 'DESMONTE']);
        Distrito::updateOrCreate(['distrito_id' => 20403, 'canton_id' => 204, 'tax_id' => 3, 'name' => 'JESUS MARIA']);
        Distrito::updateOrCreate(['distrito_id' => 20404, 'canton_id' => 204, 'tax_id' => 4, 'name' => 'LABRADOR']);
        Distrito::updateOrCreate(['distrito_id' => 20501, 'canton_id' => 205, 'tax_id' => 1, 'name' => 'ATENAS']);
        Distrito::updateOrCreate(['distrito_id' => 20502, 'canton_id' => 205, 'tax_id' => 2, 'name' => 'JESUS']);
        Distrito::updateOrCreate(['distrito_id' => 20503, 'canton_id' => 205, 'tax_id' => 3, 'name' => 'MERCEDES']);
        Distrito::updateOrCreate(['distrito_id' => 20504, 'canton_id' => 205, 'tax_id' => 4, 'name' => 'SAN ISIDRO']);
        Distrito::updateOrCreate(['distrito_id' => 20505, 'canton_id' => 205, 'tax_id' => 5, 'name' => 'CONCEPCION']);
        Distrito::updateOrCreate(['distrito_id' => 20506, 'canton_id' => 205, 'tax_id' => 6, 'name' => 'SAN JOSE']);
        Distrito::updateOrCreate(['distrito_id' => 20507, 'canton_id' => 205, 'tax_id' => 7, 'name' => 'SANTA EULALIA']);
        Distrito::updateOrCreate(['distrito_id' => 20508, 'canton_id' => 205, 'tax_id' => 8, 'name' => 'ESCOBAL']);
        Distrito::updateOrCreate(['distrito_id' => 20601, 'canton_id' => 206, 'tax_id' => 1, 'name' => 'NARANJO']);
        Distrito::updateOrCreate(['distrito_id' => 20602, 'canton_id' => 206, 'tax_id' => 2, 'name' => 'SAN MIGUEL']);
        Distrito::updateOrCreate(['distrito_id' => 20603, 'canton_id' => 206, 'tax_id' => 3, 'name' => 'SAN JOSE']);
        Distrito::updateOrCreate(['distrito_id' => 20604, 'canton_id' => 206, 'tax_id' => 4, 'name' => 'CIRRI SUR']);
        Distrito::updateOrCreate(['distrito_id' => 20605, 'canton_id' => 206, 'tax_id' => 5, 'name' => 'SAN JERONIMO']);
        Distrito::updateOrCreate(['distrito_id' => 20606, 'canton_id' => 206, 'tax_id' => 6, 'name' => 'SAN JUAN']);
        Distrito::updateOrCreate(['distrito_id' => 20607, 'canton_id' => 206, 'tax_id' => 7, 'name' => 'ROSARIO']);
        Distrito::updateOrCreate(['distrito_id' => 20608, 'canton_id' => 206, 'tax_id' => 8, 'name' => 'PALMITOS']);
        Distrito::updateOrCreate(['distrito_id' => 20701, 'canton_id' => 207, 'tax_id' => 1, 'name' => 'PALMARES']);
        Distrito::updateOrCreate(['distrito_id' => 20702, 'canton_id' => 207, 'tax_id' => 2, 'name' => 'ZARAGOZA']);
        Distrito::updateOrCreate(['distrito_id' => 20703, 'canton_id' => 207, 'tax_id' => 3, 'name' => 'BUENOS AIRES']);
        Distrito::updateOrCreate(['distrito_id' => 20704, 'canton_id' => 207, 'tax_id' => 4, 'name' => 'SANTIAGO']);
        Distrito::updateOrCreate(['distrito_id' => 20705, 'canton_id' => 207, 'tax_id' => 5, 'name' => 'CANDELARIA']);
        Distrito::updateOrCreate(['distrito_id' => 20706, 'canton_id' => 207, 'tax_id' => 6, 'name' => 'ESQUIPULAS']);
        Distrito::updateOrCreate(['distrito_id' => 20707, 'canton_id' => 207, 'tax_id' => 7, 'name' => 'GRANJA']);
        Distrito::updateOrCreate(['distrito_id' => 20801, 'canton_id' => 208, 'tax_id' => 1, 'name' => 'SAN PEDRO']);
        Distrito::updateOrCreate(['distrito_id' => 20802, 'canton_id' => 208, 'tax_id' => 2, 'name' => 'SAN JUAN']);
        Distrito::updateOrCreate(['distrito_id' => 20803, 'canton_id' => 208, 'tax_id' => 3, 'name' => 'SAN RAFAEL']);
        Distrito::updateOrCreate(['distrito_id' => 20804, 'canton_id' => 208, 'tax_id' => 4, 'name' => 'CARRILLOS']);
        Distrito::updateOrCreate(['distrito_id' => 20805, 'canton_id' => 208, 'tax_id' => 5, 'name' => 'SABANA REDONDA']);
        Distrito::updateOrCreate(['distrito_id' => 20901, 'canton_id' => 209, 'tax_id' => 1, 'name' => 'OROTINA']);
        Distrito::updateOrCreate(['distrito_id' => 20902, 'canton_id' => 209, 'tax_id' => 2, 'name' => 'MASTATE']);
        Distrito::updateOrCreate(['distrito_id' => 20903, 'canton_id' => 209, 'tax_id' => 3, 'name' => 'HACIENDA VIEJA']);
        Distrito::updateOrCreate(['distrito_id' => 20904, 'canton_id' => 209, 'tax_id' => 4, 'name' => 'COYOLAR']);
        Distrito::updateOrCreate(['distrito_id' => 20905, 'canton_id' => 209, 'tax_id' => 5, 'name' => 'CEIBA']);
        Distrito::updateOrCreate(['distrito_id' => 21001, 'canton_id' => 210, 'tax_id' => 1, 'name' => 'QUESADA']);
        Distrito::updateOrCreate(['distrito_id' => 21002, 'canton_id' => 210, 'tax_id' => 2, 'name' => 'FLORENCIA']);
        Distrito::updateOrCreate(['distrito_id' => 21003, 'canton_id' => 210, 'tax_id' => 3, 'name' => 'BUENAVISTA']);
        Distrito::updateOrCreate(['distrito_id' => 21004, 'canton_id' => 210, 'tax_id' => 4, 'name' => 'AGUAS ZARCAS']);
        Distrito::updateOrCreate(['distrito_id' => 21005, 'canton_id' => 210, 'tax_id' => 5, 'name' => 'VENECIA']);
        Distrito::updateOrCreate(['distrito_id' => 21006, 'canton_id' => 210, 'tax_id' => 6, 'name' => 'PITAL']);
        Distrito::updateOrCreate(['distrito_id' => 21007, 'canton_id' => 210, 'tax_id' => 7, 'name' => 'FORTUNA']);
        Distrito::updateOrCreate(['distrito_id' => 21008, 'canton_id' => 210, 'tax_id' => 8, 'name' => 'TIGRA']);
        Distrito::updateOrCreate(['distrito_id' => 21009, 'canton_id' => 210, 'tax_id' => 9, 'name' => 'PALMERA']);
        Distrito::updateOrCreate(['distrito_id' => 21010, 'canton_id' => 210, 'tax_id' => 10, 'name' => 'VENADO']);
        Distrito::updateOrCreate(['distrito_id' => 21011, 'canton_id' => 210, 'tax_id' => 11, 'name' => 'CUTRIS']);
        Distrito::updateOrCreate(['distrito_id' => 21012, 'canton_id' => 210, 'tax_id' => 12, 'name' => 'MONTERREY']);
        Distrito::updateOrCreate(['distrito_id' => 21013, 'canton_id' => 210, 'tax_id' => 13, 'name' => 'POCOSOL']);
        Distrito::updateOrCreate(['distrito_id' => 21101, 'canton_id' => 211, 'tax_id' => 1, 'name' => 'ZARCERO']);
        Distrito::updateOrCreate(['distrito_id' => 21102, 'canton_id' => 211, 'tax_id' => 2, 'name' => 'LAGUNA']);
        Distrito::updateOrCreate(['distrito_id' => 21103, 'canton_id' => 211, 'tax_id' => 3, 'name' => 'TAPEZCO']);
        Distrito::updateOrCreate(['distrito_id' => 21104, 'canton_id' => 211, 'tax_id' => 4, 'name' => 'GUADALUPE']);
        Distrito::updateOrCreate(['distrito_id' => 21105, 'canton_id' => 211, 'tax_id' => 5, 'name' => 'PALMIRA']);
        Distrito::updateOrCreate(['distrito_id' => 21106, 'canton_id' => 211, 'tax_id' => 6, 'name' => 'ZAPOTE']);
        Distrito::updateOrCreate(['distrito_id' => 21107, 'canton_id' => 211, 'tax_id' => 7, 'name' => 'BRISAS']);
        Distrito::updateOrCreate(['distrito_id' => 21201, 'canton_id' => 212, 'tax_id' => 1, 'name' => 'SARCHI NORTE']);
        Distrito::updateOrCreate(['distrito_id' => 21202, 'canton_id' => 212, 'tax_id' => 2, 'name' => 'SARCHI SUR']);
        Distrito::updateOrCreate(['distrito_id' => 21203, 'canton_id' => 212, 'tax_id' => 3, 'name' => 'TORO AMARILLO']);
        Distrito::updateOrCreate(['distrito_id' => 21204, 'canton_id' => 212, 'tax_id' => 4, 'name' => 'SAN PEDRO']);
        Distrito::updateOrCreate(['distrito_id' => 21205, 'canton_id' => 212, 'tax_id' => 5, 'name' => 'RODRIGUEZ']);
        Distrito::updateOrCreate(['distrito_id' => 21301, 'canton_id' => 213, 'tax_id' => 1, 'name' => 'UPALA']);
        Distrito::updateOrCreate(['distrito_id' => 21302, 'canton_id' => 213, 'tax_id' => 2, 'name' => 'AGUAS CLARAS']);
        Distrito::updateOrCreate(['distrito_id' => 21303, 'canton_id' => 213, 'tax_id' => 3, 'name' => 'SAN JOSE O PIZOTE']);
        Distrito::updateOrCreate(['distrito_id' => 21304, 'canton_id' => 213, 'tax_id' => 4, 'name' => 'BIJAGUA']);
        Distrito::updateOrCreate(['distrito_id' => 21305, 'canton_id' => 213, 'tax_id' => 5, 'name' => 'DELICIAS']);
        Distrito::updateOrCreate(['distrito_id' => 21306, 'canton_id' => 213, 'tax_id' => 6, 'name' => 'DOS RIOS']);
        Distrito::updateOrCreate(['distrito_id' => 21307, 'canton_id' => 213, 'tax_id' => 7, 'name' => 'YOLILLAL']);
        Distrito::updateOrCreate(['distrito_id' => 21308, 'canton_id' => 213, 'tax_id' => 8, 'name' => 'CANALETE']);
        Distrito::updateOrCreate(['distrito_id' => 21401, 'canton_id' => 214, 'tax_id' => 1, 'name' => 'LOS CHILES']);
        Distrito::updateOrCreate(['distrito_id' => 21402, 'canton_id' => 214, 'tax_id' => 2, 'name' => 'CAÑO NEGRO']);
        Distrito::updateOrCreate(['distrito_id' => 21403, 'canton_id' => 214, 'tax_id' => 3, 'name' => 'EL AMPARO']);
        Distrito::updateOrCreate(['distrito_id' => 21404, 'canton_id' => 214, 'tax_id' => 4, 'name' => 'SAN JORGE']);
        Distrito::updateOrCreate(['distrito_id' => 21501, 'canton_id' => 215, 'tax_id' => 1, 'name' => 'SAN RAFAEL']);
        Distrito::updateOrCreate(['distrito_id' => 21502, 'canton_id' => 215, 'tax_id' => 2, 'name' => 'BUENA VISTA']);
        Distrito::updateOrCreate(['distrito_id' => 21503, 'canton_id' => 215, 'tax_id' => 3, 'name' => 'COTE']);
        Distrito::updateOrCreate(['distrito_id' => 21504, 'canton_id' => 215, 'tax_id' => 4, 'name' => 'KATIRA']);
        Distrito::updateOrCreate(['distrito_id' => 21601, 'canton_id' => 216, 'tax_id' => 1, 'name' => 'RIO CUARTO']);
        Distrito::updateOrCreate(['distrito_id' => 30101, 'canton_id' => 301, 'tax_id' => 1, 'name' => 'ORIENTAL (Ciudad de Cartago parte)']);
        Distrito::updateOrCreate(['distrito_id' => 30102, 'canton_id' => 301, 'tax_id' => 2, 'name' => 'OCCIDENTAL (Ciudad de Cartago parte)']);
        Distrito::updateOrCreate(['distrito_id' => 30103, 'canton_id' => 301, 'tax_id' => 3, 'name' => 'CARMEN']);
        Distrito::updateOrCreate(['distrito_id' => 30104, 'canton_id' => 301, 'tax_id' => 4, 'name' => 'SAN NICOLAS']);
        Distrito::updateOrCreate(['distrito_id' => 30105, 'canton_id' => 301, 'tax_id' => 5, 'name' => 'AGUACALIENTE o SAN FRANCISCO']);
        Distrito::updateOrCreate(['distrito_id' => 30106, 'canton_id' => 301, 'tax_id' => 6, 'name' => 'GUADALUPE']);
        Distrito::updateOrCreate(['distrito_id' => 30107, 'canton_id' => 301, 'tax_id' => 7, 'name' => 'CORRALILLO']);
        Distrito::updateOrCreate(['distrito_id' => 30108, 'canton_id' => 301, 'tax_id' => 8, 'name' => 'TIERRA BLANCA']);
        Distrito::updateOrCreate(['distrito_id' => 30109, 'canton_id' => 301, 'tax_id' => 9, 'name' => 'DULCE NOMBRE']);
        Distrito::updateOrCreate(['distrito_id' => 30110, 'canton_id' => 301, 'tax_id' => 10, 'name' => 'LLANO GRANDE']);
        Distrito::updateOrCreate(['distrito_id' => 30111, 'canton_id' => 301, 'tax_id' => 11, 'name' => 'QUEBRADILLA']);
        Distrito::updateOrCreate(['distrito_id' => 30201, 'canton_id' => 302, 'tax_id' => 1, 'name' => 'PARAISO']);
        Distrito::updateOrCreate(['distrito_id' => 30202, 'canton_id' => 302, 'tax_id' => 2, 'name' => 'SANTIAGO']);
        Distrito::updateOrCreate(['distrito_id' => 30203, 'canton_id' => 302, 'tax_id' => 3, 'name' => 'OROSI']);
        Distrito::updateOrCreate(['distrito_id' => 30204, 'canton_id' => 302, 'tax_id' => 4, 'name' => 'CACHI']);
        Distrito::updateOrCreate(['distrito_id' => 30205, 'canton_id' => 302, 'tax_id' => 5, 'name' => 'LLANOS DE SANTA LUCIA']);
        Distrito::updateOrCreate(['distrito_id' => 30301, 'canton_id' => 303, 'tax_id' => 1, 'name' => 'TRES RIOS']);
        Distrito::updateOrCreate(['distrito_id' => 30302, 'canton_id' => 303, 'tax_id' => 2, 'name' => 'SAN DIEGO']);
        Distrito::updateOrCreate(['distrito_id' => 30303, 'canton_id' => 303, 'tax_id' => 3, 'name' => 'SAN JUAN']);
        Distrito::updateOrCreate(['distrito_id' => 30304, 'canton_id' => 303, 'tax_id' => 4, 'name' => 'SAN RAFAEL']);
        Distrito::updateOrCreate(['distrito_id' => 30305, 'canton_id' => 303, 'tax_id' => 5, 'name' => 'CONCEPCION']);
        Distrito::updateOrCreate(['distrito_id' => 30306, 'canton_id' => 303, 'tax_id' => 6, 'name' => 'DULCE NOMBRE']);
        Distrito::updateOrCreate(['distrito_id' => 30307, 'canton_id' => 303, 'tax_id' => 7, 'name' => 'SAN RAMON']);
        Distrito::updateOrCreate(['distrito_id' => 30308, 'canton_id' => 303, 'tax_id' => 8, 'name' => 'RIO AZUL']);
        Distrito::updateOrCreate(['distrito_id' => 30401, 'canton_id' => 304, 'tax_id' => 1, 'name' => 'JUAN VIÑAS']);
        Distrito::updateOrCreate(['distrito_id' => 30402, 'canton_id' => 304, 'tax_id' => 2, 'name' => 'TUCURRIQUE']);
        Distrito::updateOrCreate(['distrito_id' => 30403, 'canton_id' => 304, 'tax_id' => 3, 'name' => 'PEJIBAYE']);
        Distrito::updateOrCreate(['distrito_id' => 30501, 'canton_id' => 305, 'tax_id' => 1, 'name' => 'TURRIALBA']);
        Distrito::updateOrCreate(['distrito_id' => 30502, 'canton_id' => 305, 'tax_id' => 2, 'name' => 'LA SUIZA']);
        Distrito::updateOrCreate(['distrito_id' => 30503, 'canton_id' => 305, 'tax_id' => 3, 'name' => 'PERALTA']);
        Distrito::updateOrCreate(['distrito_id' => 30504, 'canton_id' => 305, 'tax_id' => 4, 'name' => 'SANTA CRUZ']);
        Distrito::updateOrCreate(['distrito_id' => 30505, 'canton_id' => 305, 'tax_id' => 5, 'name' => 'SANTA TERESITA']);
        Distrito::updateOrCreate(['distrito_id' => 30506, 'canton_id' => 305, 'tax_id' => 6, 'name' => 'PAVONES']);
        Distrito::updateOrCreate(['distrito_id' => 30507, 'canton_id' => 305, 'tax_id' => 7, 'name' => 'TUIS']);
        Distrito::updateOrCreate(['distrito_id' => 30508, 'canton_id' => 305, 'tax_id' => 8, 'name' => 'TAYUTIC']);
        Distrito::updateOrCreate(['distrito_id' => 30509, 'canton_id' => 305, 'tax_id' => 9, 'name' => 'SANTA ROSA']);
        Distrito::updateOrCreate(['distrito_id' => 30510, 'canton_id' => 305, 'tax_id' => 10, 'name' => 'TRES EQUIS']);
        Distrito::updateOrCreate(['distrito_id' => 30511, 'canton_id' => 305, 'tax_id' => 11, 'name' => 'ISABEL']);
        Distrito::updateOrCreate(['distrito_id' => 30512, 'canton_id' => 305, 'tax_id' => 12, 'name' => 'CHIRRIPO']);
        Distrito::updateOrCreate(['distrito_id' => 30601, 'canton_id' => 306, 'tax_id' => 1, 'name' => 'PACAYAS']);
        Distrito::updateOrCreate(['distrito_id' => 30602, 'canton_id' => 306, 'tax_id' => 2, 'name' => 'CERVANTES']);
        Distrito::updateOrCreate(['distrito_id' => 30603, 'canton_id' => 306, 'tax_id' => 3, 'name' => 'CAPELLADES']);
        Distrito::updateOrCreate(['distrito_id' => 30701, 'canton_id' => 307, 'tax_id' => 1, 'name' => 'SAN RAFAEL']);
        Distrito::updateOrCreate(['distrito_id' => 30702, 'canton_id' => 307, 'tax_id' => 2, 'name' => 'COT']);
        Distrito::updateOrCreate(['distrito_id' => 30703, 'canton_id' => 307, 'tax_id' => 3, 'name' => 'POTRERO CERRADO']);
        Distrito::updateOrCreate(['distrito_id' => 30704, 'canton_id' => 307, 'tax_id' => 4, 'name' => 'CIPRESES']);
        Distrito::updateOrCreate(['distrito_id' => 30705, 'canton_id' => 307, 'tax_id' => 5, 'name' => 'SANTA ROSA']);
        Distrito::updateOrCreate(['distrito_id' => 30801, 'canton_id' => 308, 'tax_id' => 1, 'name' => 'TEJAR']);
        Distrito::updateOrCreate(['distrito_id' => 30802, 'canton_id' => 308, 'tax_id' => 2, 'name' => 'SAN ISIDRO']);
        Distrito::updateOrCreate(['distrito_id' => 30803, 'canton_id' => 308, 'tax_id' => 3, 'name' => 'TOBOSI']);
        Distrito::updateOrCreate(['distrito_id' => 30804, 'canton_id' => 308, 'tax_id' => 4, 'name' => 'PATIO DE AGUA']);
        Distrito::updateOrCreate(['distrito_id' => 40101, 'canton_id' => 401, 'tax_id' => 1, 'name' => 'HEREDIA']);
        Distrito::updateOrCreate(['distrito_id' => 40102, 'canton_id' => 401, 'tax_id' => 2, 'name' => 'MERCEDES']);
        Distrito::updateOrCreate(['distrito_id' => 40103, 'canton_id' => 401, 'tax_id' => 3, 'name' => 'SAN FRANCISCO']);
        Distrito::updateOrCreate(['distrito_id' => 40104, 'canton_id' => 401, 'tax_id' => 4, 'name' => 'ULLOA O BARREAL']);
        Distrito::updateOrCreate(['distrito_id' => 40105, 'canton_id' => 401, 'tax_id' => 5, 'name' => 'VARA BLANCA']);
        Distrito::updateOrCreate(['distrito_id' => 40201, 'canton_id' => 402, 'tax_id' => 1, 'name' => 'BARVA']);
        Distrito::updateOrCreate(['distrito_id' => 40202, 'canton_id' => 402, 'tax_id' => 2, 'name' => 'SAN PEDRO']);
        Distrito::updateOrCreate(['distrito_id' => 40203, 'canton_id' => 402, 'tax_id' => 3, 'name' => 'SAN PABLO']);
        Distrito::updateOrCreate(['distrito_id' => 40204, 'canton_id' => 402, 'tax_id' => 4, 'name' => 'SAN ROQUE']);
        Distrito::updateOrCreate(['distrito_id' => 40205, 'canton_id' => 402, 'tax_id' => 5, 'name' => 'SANTA LUCIA']);
        Distrito::updateOrCreate(['distrito_id' => 40206, 'canton_id' => 402, 'tax_id' => 6, 'name' => 'SAN JOSE DE LA MONTAÑA']);
        Distrito::updateOrCreate(['distrito_id' => 40301, 'canton_id' => 403, 'tax_id' => 1, 'name' => 'SANTO DOMINGO']);
        Distrito::updateOrCreate(['distrito_id' => 40302, 'canton_id' => 403, 'tax_id' => 2, 'name' => 'SAN VICENTE']);
        Distrito::updateOrCreate(['distrito_id' => 40303, 'canton_id' => 403, 'tax_id' => 3, 'name' => 'SAN MIGUEL']);
        Distrito::updateOrCreate(['distrito_id' => 40304, 'canton_id' => 403, 'tax_id' => 4, 'name' => 'PARACITO']);
        Distrito::updateOrCreate(['distrito_id' => 40305, 'canton_id' => 403, 'tax_id' => 5, 'name' => 'SANTO TOMAS']);
        Distrito::updateOrCreate(['distrito_id' => 40306, 'canton_id' => 403, 'tax_id' => 6, 'name' => 'SANTA ROSA']);
        Distrito::updateOrCreate(['distrito_id' => 40307, 'canton_id' => 403, 'tax_id' => 7, 'name' => 'TURES']);
        Distrito::updateOrCreate(['distrito_id' => 40308, 'canton_id' => 403, 'tax_id' => 8, 'name' => 'PARA']);
        Distrito::updateOrCreate(['distrito_id' => 40401, 'canton_id' => 404, 'tax_id' => 1, 'name' => 'SANTA BARBARA']);
        Distrito::updateOrCreate(['distrito_id' => 40402, 'canton_id' => 404, 'tax_id' => 2, 'name' => 'SAN PEDRO']);
        Distrito::updateOrCreate(['distrito_id' => 40403, 'canton_id' => 404, 'tax_id' => 3, 'name' => 'SAN JUAN']);
        Distrito::updateOrCreate(['distrito_id' => 40404, 'canton_id' => 404, 'tax_id' => 4, 'name' => 'JESUS']);
        Distrito::updateOrCreate(['distrito_id' => 40405, 'canton_id' => 404, 'tax_id' => 5, 'name' => 'SANTO DOMINGO']);
        Distrito::updateOrCreate(['distrito_id' => 40406, 'canton_id' => 404, 'tax_id' => 6, 'name' => 'PURABA']);
        Distrito::updateOrCreate(['distrito_id' => 40501, 'canton_id' => 405, 'tax_id' => 1, 'name' => 'SAN RAFAEL']);
        Distrito::updateOrCreate(['distrito_id' => 40502, 'canton_id' => 405, 'tax_id' => 2, 'name' => 'SAN JOSECITO']);
        Distrito::updateOrCreate(['distrito_id' => 40503, 'canton_id' => 405, 'tax_id' => 3, 'name' => 'SANTIAGO']);
        Distrito::updateOrCreate(['distrito_id' => 40504, 'canton_id' => 405, 'tax_id' => 4, 'name' => 'ANGELES']);
        Distrito::updateOrCreate(['distrito_id' => 40505, 'canton_id' => 405, 'tax_id' => 5, 'name' => 'CONCEPCION']);
        Distrito::updateOrCreate(['distrito_id' => 40601, 'canton_id' => 406, 'tax_id' => 1, 'name' => 'SAN ISIDRO']);
        Distrito::updateOrCreate(['distrito_id' => 40602, 'canton_id' => 406, 'tax_id' => 2, 'name' => 'SAN JOSE']);
        Distrito::updateOrCreate(['distrito_id' => 40603, 'canton_id' => 406, 'tax_id' => 3, 'name' => 'CONCEPCION']);
        Distrito::updateOrCreate(['distrito_id' => 40604, 'canton_id' => 406, 'tax_id' => 4, 'name' => 'SAN FRANCISO']);
        Distrito::updateOrCreate(['distrito_id' => 40701, 'canton_id' => 407, 'tax_id' => 1, 'name' => 'SAN ANTONIO']);
        Distrito::updateOrCreate(['distrito_id' => 40702, 'canton_id' => 407, 'tax_id' => 2, 'name' => 'RIVERA']);
        Distrito::updateOrCreate(['distrito_id' => 40703, 'canton_id' => 407, 'tax_id' => 3, 'name' => 'ASUNCION']);
        Distrito::updateOrCreate(['distrito_id' => 40801, 'canton_id' => 408, 'tax_id' => 1, 'name' => 'SAN JOAQUIN']);
        Distrito::updateOrCreate(['distrito_id' => 40802, 'canton_id' => 408, 'tax_id' => 2, 'name' => 'BARRANTES']);
        Distrito::updateOrCreate(['distrito_id' => 40803, 'canton_id' => 408, 'tax_id' => 3, 'name' => 'LLORENTE']);
        Distrito::updateOrCreate(['distrito_id' => 40901, 'canton_id' => 409, 'tax_id' => 1, 'name' => 'SAN PABLO']);
        Distrito::updateOrCreate(['distrito_id' => 40902, 'canton_id' => 409, 'tax_id' => 2, 'name' => 'RINCON DE SABANILLA']);
        Distrito::updateOrCreate(['distrito_id' => 41001, 'canton_id' => 410, 'tax_id' => 1, 'name' => 'PUERTO VIEJO SARAPIQUI']);
        Distrito::updateOrCreate(['distrito_id' => 41002, 'canton_id' => 410, 'tax_id' => 2, 'name' => 'LA VIRGEN']);
        Distrito::updateOrCreate(['distrito_id' => 41003, 'canton_id' => 410, 'tax_id' => 3, 'name' => 'HORQUETAS']);
        Distrito::updateOrCreate(['distrito_id' => 41004, 'canton_id' => 410, 'tax_id' => 4, 'name' => 'LLANURAS DEL GASPAR']);
        Distrito::updateOrCreate(['distrito_id' => 41005, 'canton_id' => 410, 'tax_id' => 5, 'name' => 'CUREÑA']);
        Distrito::updateOrCreate(['distrito_id' => 50101, 'canton_id' => 501, 'tax_id' => 1, 'name' => 'LIBERIA']);
        Distrito::updateOrCreate(['distrito_id' => 50102, 'canton_id' => 501, 'tax_id' => 2, 'name' => 'CAÑAS DULCES']);
        Distrito::updateOrCreate(['distrito_id' => 50103, 'canton_id' => 501, 'tax_id' => 3, 'name' => 'MAYORGA']);
        Distrito::updateOrCreate(['distrito_id' => 50104, 'canton_id' => 501, 'tax_id' => 4, 'name' => 'NACASCOLO']);
        Distrito::updateOrCreate(['distrito_id' => 50105, 'canton_id' => 501, 'tax_id' => 5, 'name' => 'CURUBANDE']);
        Distrito::updateOrCreate(['distrito_id' => 50201, 'canton_id' => 502, 'tax_id' => 1, 'name' => 'NICOYA']);
        Distrito::updateOrCreate(['distrito_id' => 50202, 'canton_id' => 502, 'tax_id' => 2, 'name' => 'MANSION']);
        Distrito::updateOrCreate(['distrito_id' => 50203, 'canton_id' => 502, 'tax_id' => 3, 'name' => 'SAN ANTONIO']);
        Distrito::updateOrCreate(['distrito_id' => 50204, 'canton_id' => 502, 'tax_id' => 4, 'name' => 'QUEBRADA HONDA']);
        Distrito::updateOrCreate(['distrito_id' => 50205, 'canton_id' => 502, 'tax_id' => 5, 'name' => 'SAMARA']);
        Distrito::updateOrCreate(['distrito_id' => 50206, 'canton_id' => 502, 'tax_id' => 6, 'name' => 'NOSARA']);
        Distrito::updateOrCreate(['distrito_id' => 50207, 'canton_id' => 502, 'tax_id' => 7, 'name' => 'BELEN DE NOSARITA']);
        Distrito::updateOrCreate(['distrito_id' => 50301, 'canton_id' => 503, 'tax_id' => 1, 'name' => 'SANTA CRUZ']);
        Distrito::updateOrCreate(['distrito_id' => 50302, 'canton_id' => 503, 'tax_id' => 2, 'name' => 'BOLSON']);
        Distrito::updateOrCreate(['distrito_id' => 50303, 'canton_id' => 503, 'tax_id' => 3, 'name' => 'VEINTISIETE DE ABRIL']);
        Distrito::updateOrCreate(['distrito_id' => 50304, 'canton_id' => 503, 'tax_id' => 4, 'name' => 'TEMPATE']);
        Distrito::updateOrCreate(['distrito_id' => 50305, 'canton_id' => 503, 'tax_id' => 5, 'name' => 'CARTAGENA']);
        Distrito::updateOrCreate(['distrito_id' => 50306, 'canton_id' => 503, 'tax_id' => 6, 'name' => 'CUAJINIQUIL']);
        Distrito::updateOrCreate(['distrito_id' => 50307, 'canton_id' => 503, 'tax_id' => 7, 'name' => 'DIRIA']);
        Distrito::updateOrCreate(['distrito_id' => 50308, 'canton_id' => 503, 'tax_id' => 8, 'name' => 'CABO VELAS']);
        Distrito::updateOrCreate(['distrito_id' => 50309, 'canton_id' => 503, 'tax_id' => 9, 'name' => 'TAMARINDO']);
        Distrito::updateOrCreate(['distrito_id' => 50401, 'canton_id' => 504, 'tax_id' => 1, 'name' => 'BAGACES']);
        Distrito::updateOrCreate(['distrito_id' => 50402, 'canton_id' => 504, 'tax_id' => 2, 'name' => 'FORTUNA']);
        Distrito::updateOrCreate(['distrito_id' => 50403, 'canton_id' => 504, 'tax_id' => 3, 'name' => 'MOGOTE']);
        Distrito::updateOrCreate(['distrito_id' => 50404, 'canton_id' => 504, 'tax_id' => 4, 'name' => 'RIO NARANJO']);
        Distrito::updateOrCreate(['distrito_id' => 50501, 'canton_id' => 505, 'tax_id' => 1, 'name' => 'FILADELFIA']);
        Distrito::updateOrCreate(['distrito_id' => 50502, 'canton_id' => 505, 'tax_id' => 2, 'name' => 'PALMIRA']);
        Distrito::updateOrCreate(['distrito_id' => 50503, 'canton_id' => 505, 'tax_id' => 3, 'name' => 'SARDINAL']);
        Distrito::updateOrCreate(['distrito_id' => 50504, 'canton_id' => 505, 'tax_id' => 4, 'name' => 'BELEN']);
        Distrito::updateOrCreate(['distrito_id' => 50601, 'canton_id' => 506, 'tax_id' => 1, 'name' => 'CAÑAS']);
        Distrito::updateOrCreate(['distrito_id' => 50602, 'canton_id' => 506, 'tax_id' => 2, 'name' => 'PALMIRA']);
        Distrito::updateOrCreate(['distrito_id' => 50603, 'canton_id' => 506, 'tax_id' => 3, 'name' => 'SAN MIGUEL']);
        Distrito::updateOrCreate(['distrito_id' => 50604, 'canton_id' => 506, 'tax_id' => 4, 'name' => 'BEBEDERO']);
        Distrito::updateOrCreate(['distrito_id' => 50605, 'canton_id' => 506, 'tax_id' => 5, 'name' => 'POROZAL']);
        Distrito::updateOrCreate(['distrito_id' => 50701, 'canton_id' => 507, 'tax_id' => 1, 'name' => 'JUNTAS']);
        Distrito::updateOrCreate(['distrito_id' => 50702, 'canton_id' => 507, 'tax_id' => 2, 'name' => 'SIERRA']);
        Distrito::updateOrCreate(['distrito_id' => 50703, 'canton_id' => 507, 'tax_id' => 3, 'name' => 'SAN JUAN']);
        Distrito::updateOrCreate(['distrito_id' => 50704, 'canton_id' => 507, 'tax_id' => 4, 'name' => 'COLORADO']);
        Distrito::updateOrCreate(['distrito_id' => 50801, 'canton_id' => 508, 'tax_id' => 1, 'name' => 'TILARAN']);
        Distrito::updateOrCreate(['distrito_id' => 50802, 'canton_id' => 508, 'tax_id' => 2, 'name' => 'QUEBRADA GRANDE']);
        Distrito::updateOrCreate(['distrito_id' => 50803, 'canton_id' => 508, 'tax_id' => 3, 'name' => 'TRONADORA']);
        Distrito::updateOrCreate(['distrito_id' => 50804, 'canton_id' => 508, 'tax_id' => 4, 'name' => 'SANTA ROSA']);
        Distrito::updateOrCreate(['distrito_id' => 50805, 'canton_id' => 508, 'tax_id' => 5, 'name' => 'LIBANO']);
        Distrito::updateOrCreate(['distrito_id' => 50806, 'canton_id' => 508, 'tax_id' => 6, 'name' => 'TIERRAS MORENAS']);
        Distrito::updateOrCreate(['distrito_id' => 50807, 'canton_id' => 508, 'tax_id' => 7, 'name' => 'ARENAL']);
        Distrito::updateOrCreate(['distrito_id' => 50901, 'canton_id' => 509, 'tax_id' => 1, 'name' => 'CARMONA']);
        Distrito::updateOrCreate(['distrito_id' => 50902, 'canton_id' => 509, 'tax_id' => 2, 'name' => 'SANTA RITA']);
        Distrito::updateOrCreate(['distrito_id' => 50903, 'canton_id' => 509, 'tax_id' => 3, 'name' => 'ZAPOTAL']);
        Distrito::updateOrCreate(['distrito_id' => 50904, 'canton_id' => 509, 'tax_id' => 4, 'name' => 'SAN PABLO']);
        Distrito::updateOrCreate(['distrito_id' => 50905, 'canton_id' => 509, 'tax_id' => 5, 'name' => 'PROVENIR']);
        Distrito::updateOrCreate(['distrito_id' => 50906, 'canton_id' => 509, 'tax_id' => 6, 'name' => 'BEJUCO']);
        Distrito::updateOrCreate(['distrito_id' => 51001, 'canton_id' => 510, 'tax_id' => 1, 'name' => 'LA CRUZ']);
        Distrito::updateOrCreate(['distrito_id' => 51002, 'canton_id' => 510, 'tax_id' => 2, 'name' => 'SANTA CECILIA']);
        Distrito::updateOrCreate(['distrito_id' => 51003, 'canton_id' => 510, 'tax_id' => 3, 'name' => 'GARITA']);
        Distrito::updateOrCreate(['distrito_id' => 51004, 'canton_id' => 510, 'tax_id' => 4, 'name' => 'SANTA ELENA']);
        Distrito::updateOrCreate(['distrito_id' => 51101, 'canton_id' => 511, 'tax_id' => 1, 'name' => 'HOJANCHA']);
        Distrito::updateOrCreate(['distrito_id' => 51102, 'canton_id' => 511, 'tax_id' => 2, 'name' => 'MONTE ROMO']);
        Distrito::updateOrCreate(['distrito_id' => 51103, 'canton_id' => 511, 'tax_id' => 3, 'name' => 'PUERTO CARRILLO']);
        Distrito::updateOrCreate(['distrito_id' => 51104, 'canton_id' => 511, 'tax_id' => 4, 'name' => 'HUACAS']);
        Distrito::updateOrCreate(['distrito_id' => 60101, 'canton_id' => 601, 'tax_id' => 1, 'name' => 'PUNTARENAS']);
        Distrito::updateOrCreate(['distrito_id' => 60102, 'canton_id' => 601, 'tax_id' => 2, 'name' => 'PITAHAYA']);
        Distrito::updateOrCreate(['distrito_id' => 60103, 'canton_id' => 601, 'tax_id' => 3, 'name' => 'CHOMES']);
        Distrito::updateOrCreate(['distrito_id' => 60104, 'canton_id' => 601, 'tax_id' => 4, 'name' => 'LEPANTO']);
        Distrito::updateOrCreate(['distrito_id' => 60105, 'canton_id' => 601, 'tax_id' => 5, 'name' => 'PAQUERA']);
        Distrito::updateOrCreate(['distrito_id' => 60106, 'canton_id' => 601, 'tax_id' => 6, 'name' => 'MANZANILLO']);
        Distrito::updateOrCreate(['distrito_id' => 60107, 'canton_id' => 601, 'tax_id' => 7, 'name' => 'GUACIMAL']);
        Distrito::updateOrCreate(['distrito_id' => 60108, 'canton_id' => 601, 'tax_id' => 8, 'name' => 'BARRANCA']);
        Distrito::updateOrCreate(['distrito_id' => 60109, 'canton_id' => 601, 'tax_id' => 9, 'name' => 'MONTE VERDE']);
        Distrito::updateOrCreate(['distrito_id' => 60110, 'canton_id' => 601, 'tax_id' => 10, 'name' => 'ISLA DEL COCO']);
        Distrito::updateOrCreate(['distrito_id' => 60111, 'canton_id' => 601, 'tax_id' => 11, 'name' => 'COBANO']);
        Distrito::updateOrCreate(['distrito_id' => 60112, 'canton_id' => 601, 'tax_id' => 12, 'name' => 'CHACARITA']);
        Distrito::updateOrCreate(['distrito_id' => 60113, 'canton_id' => 601, 'tax_id' => 13, 'name' => 'CHIRA']);
        Distrito::updateOrCreate(['distrito_id' => 60114, 'canton_id' => 601, 'tax_id' => 14, 'name' => 'ACAPULCO']);
        Distrito::updateOrCreate(['distrito_id' => 60115, 'canton_id' => 601, 'tax_id' => 15, 'name' => 'EL ROBLE']);
        Distrito::updateOrCreate(['distrito_id' => 60116, 'canton_id' => 601, 'tax_id' => 16, 'name' => 'ARANCIBIA']);
        Distrito::updateOrCreate(['distrito_id' => 60201, 'canton_id' => 602, 'tax_id' => 1, 'name' => 'ESPIRITU SANTO']);
        Distrito::updateOrCreate(['distrito_id' => 60202, 'canton_id' => 602, 'tax_id' => 2, 'name' => 'SAN JUAN GRANDE']);
        Distrito::updateOrCreate(['distrito_id' => 60203, 'canton_id' => 602, 'tax_id' => 3, 'name' => 'MACACONA']);
        Distrito::updateOrCreate(['distrito_id' => 60204, 'canton_id' => 602, 'tax_id' => 4, 'name' => 'SAN RAFAEL']);
        Distrito::updateOrCreate(['distrito_id' => 60205, 'canton_id' => 602, 'tax_id' => 5, 'name' => 'SAN JERONIMO']);
        Distrito::updateOrCreate(['distrito_id' => 60206, 'canton_id' => 602, 'tax_id' => 6, 'name' => 'CALDERA']);
        Distrito::updateOrCreate(['distrito_id' => 60301, 'canton_id' => 603, 'tax_id' => 1, 'name' => 'BUENOS AIRES']);
        Distrito::updateOrCreate(['distrito_id' => 60302, 'canton_id' => 603, 'tax_id' => 2, 'name' => 'VOLCAN']);
        Distrito::updateOrCreate(['distrito_id' => 60303, 'canton_id' => 603, 'tax_id' => 3, 'name' => 'POTRERO GRANDE']);
        Distrito::updateOrCreate(['distrito_id' => 60304, 'canton_id' => 603, 'tax_id' => 4, 'name' => 'BORUCA']);
        Distrito::updateOrCreate(['distrito_id' => 60305, 'canton_id' => 603, 'tax_id' => 5, 'name' => 'PILAS']);
        Distrito::updateOrCreate(['distrito_id' => 60306, 'canton_id' => 603, 'tax_id' => 6, 'name' => 'COLINAS']);
        Distrito::updateOrCreate(['distrito_id' => 60307, 'canton_id' => 603, 'tax_id' => 7, 'name' => 'CHANGUENA']);
        Distrito::updateOrCreate(['distrito_id' => 60308, 'canton_id' => 603, 'tax_id' => 8, 'name' => 'BIOLLEY']);
        Distrito::updateOrCreate(['distrito_id' => 60309, 'canton_id' => 603, 'tax_id' => 9, 'name' => 'BRUNKA']);
        Distrito::updateOrCreate(['distrito_id' => 60401, 'canton_id' => 604, 'tax_id' => 1, 'name' => 'MIRAMAR']);
        Distrito::updateOrCreate(['distrito_id' => 60402, 'canton_id' => 604, 'tax_id' => 2, 'name' => 'UNION']);
        Distrito::updateOrCreate(['distrito_id' => 60403, 'canton_id' => 604, 'tax_id' => 3, 'name' => 'SAN ISIDRO']);
        Distrito::updateOrCreate(['distrito_id' => 60501, 'canton_id' => 605, 'tax_id' => 1, 'name' => 'PUERTO CORTES']);
        Distrito::updateOrCreate(['distrito_id' => 60502, 'canton_id' => 605, 'tax_id' => 2, 'name' => 'PALMAR']);
        Distrito::updateOrCreate(['distrito_id' => 60503, 'canton_id' => 605, 'tax_id' => 3, 'name' => 'SIERPE']);
        Distrito::updateOrCreate(['distrito_id' => 60504, 'canton_id' => 605, 'tax_id' => 4, 'name' => 'BAHIA BALLENA']);
        Distrito::updateOrCreate(['distrito_id' => 60505, 'canton_id' => 605, 'tax_id' => 5, 'name' => 'PIEDRAS BLANCAS']);
        Distrito::updateOrCreate(['distrito_id' => 60506, 'canton_id' => 605, 'tax_id' => 6, 'name' => 'BAHÍA DRAKE']);
        Distrito::updateOrCreate(['distrito_id' => 60601, 'canton_id' => 606, 'tax_id' => 1, 'name' => 'QUEPOS']);
        Distrito::updateOrCreate(['distrito_id' => 60602, 'canton_id' => 606, 'tax_id' => 2, 'name' => 'SAVEGRE']);
        Distrito::updateOrCreate(['distrito_id' => 60603, 'canton_id' => 606, 'tax_id' => 3, 'name' => 'NARANJITO']);
        Distrito::updateOrCreate(['distrito_id' => 60701, 'canton_id' => 607, 'tax_id' => 1, 'name' => 'GOLFITO']);
        Distrito::updateOrCreate(['distrito_id' => 60702, 'canton_id' => 607, 'tax_id' => 2, 'name' => 'PUERTO JIMENEZ']);
        Distrito::updateOrCreate(['distrito_id' => 60703, 'canton_id' => 607, 'tax_id' => 3, 'name' => 'GUAYCARA']);
        Distrito::updateOrCreate(['distrito_id' => 60704, 'canton_id' => 607, 'tax_id' => 4, 'name' => 'PAVON']);
        Distrito::updateOrCreate(['distrito_id' => 60801, 'canton_id' => 608, 'tax_id' => 1, 'name' => 'SAN VITO']);
        Distrito::updateOrCreate(['distrito_id' => 60802, 'canton_id' => 608, 'tax_id' => 2, 'name' => 'SABALITO']);
        Distrito::updateOrCreate(['distrito_id' => 60803, 'canton_id' => 608, 'tax_id' => 3, 'name' => 'AGUABUENA']);
        Distrito::updateOrCreate(['distrito_id' => 60804, 'canton_id' => 608, 'tax_id' => 4, 'name' => 'LIMONCITO']);
        Distrito::updateOrCreate(['distrito_id' => 60805, 'canton_id' => 608, 'tax_id' => 5, 'name' => 'PITTIER']);
        Distrito::updateOrCreate(['distrito_id' => 60806, 'canton_id' => 608, 'tax_id' => 6, 'name' => 'GUTIERREZ BRAUN']);
        Distrito::updateOrCreate(['distrito_id' => 60901, 'canton_id' => 609, 'tax_id' => 1, 'name' => 'PARRITA']);
        Distrito::updateOrCreate(['distrito_id' => 61001, 'canton_id' => 610, 'tax_id' => 1, 'name' => 'CORREDOR']);
        Distrito::updateOrCreate(['distrito_id' => 61002, 'canton_id' => 610, 'tax_id' => 2, 'name' => 'LA CUESTA']);
        Distrito::updateOrCreate(['distrito_id' => 61003, 'canton_id' => 610, 'tax_id' => 3, 'name' => 'CANOAS']);
        Distrito::updateOrCreate(['distrito_id' => 61004, 'canton_id' => 610, 'tax_id' => 4, 'name' => 'LAUREL']);
        Distrito::updateOrCreate(['distrito_id' => 61101, 'canton_id' => 611, 'tax_id' => 1, 'name' => 'JACO']);
        Distrito::updateOrCreate(['distrito_id' => 61102, 'canton_id' => 611, 'tax_id' => 2, 'name' => 'TARCOLES']);
        Distrito::updateOrCreate(['distrito_id' => 70101, 'canton_id' => 701, 'tax_id' => 1, 'name' => 'LIMON']);
        Distrito::updateOrCreate(['distrito_id' => 70102, 'canton_id' => 701, 'tax_id' => 2, 'name' => 'VALLE LA ESTRELLA']);
        Distrito::updateOrCreate(['distrito_id' => 70103, 'canton_id' => 701, 'tax_id' => 3, 'name' => 'RIO BLANCO']);
        Distrito::updateOrCreate(['distrito_id' => 70104, 'canton_id' => 701, 'tax_id' => 4, 'name' => 'MATAMA']);
        Distrito::updateOrCreate(['distrito_id' => 70201, 'canton_id' => 702, 'tax_id' => 1, 'name' => 'GUAPILES']);
        Distrito::updateOrCreate(['distrito_id' => 70202, 'canton_id' => 702, 'tax_id' => 2, 'name' => 'JIMENEZ']);
        Distrito::updateOrCreate(['distrito_id' => 70203, 'canton_id' => 702, 'tax_id' => 3, 'name' => 'RITA']);
        Distrito::updateOrCreate(['distrito_id' => 70204, 'canton_id' => 702, 'tax_id' => 4, 'name' => 'ROXANA']);
        Distrito::updateOrCreate(['distrito_id' => 70205, 'canton_id' => 702, 'tax_id' => 5, 'name' => 'CARIARI']);
        Distrito::updateOrCreate(['distrito_id' => 70206, 'canton_id' => 702, 'tax_id' => 6, 'name' => 'COLORADO']);
        Distrito::updateOrCreate(['distrito_id' => 70207, 'canton_id' => 702, 'tax_id' => 7, 'name' => 'LA COLONIA']);
        Distrito::updateOrCreate(['distrito_id' => 70301, 'canton_id' => 703, 'tax_id' => 1, 'name' => 'SIQUIRRES']);
        Distrito::updateOrCreate(['distrito_id' => 70302, 'canton_id' => 703, 'tax_id' => 2, 'name' => 'PACUARITO']);
        Distrito::updateOrCreate(['distrito_id' => 70303, 'canton_id' => 703, 'tax_id' => 3, 'name' => 'FLORIDA']);
        Distrito::updateOrCreate(['distrito_id' => 70304, 'canton_id' => 703, 'tax_id' => 4, 'name' => 'GERMANIA']);
        Distrito::updateOrCreate(['distrito_id' => 70305, 'canton_id' => 703, 'tax_id' => 5, 'name' => 'CAIRO']);
        Distrito::updateOrCreate(['distrito_id' => 70306, 'canton_id' => 703, 'tax_id' => 6, 'name' => 'ALEGRIA']);
        Distrito::updateOrCreate(['distrito_id' => 70401, 'canton_id' => 704, 'tax_id' => 1, 'name' => 'BRATSI']);
        Distrito::updateOrCreate(['distrito_id' => 70402, 'canton_id' => 704, 'tax_id' => 2, 'name' => 'SIXAOLA']);
        Distrito::updateOrCreate(['distrito_id' => 70403, 'canton_id' => 704, 'tax_id' => 3, 'name' => 'CAHUITA']);
        Distrito::updateOrCreate(['distrito_id' => 70404, 'canton_id' => 704, 'tax_id' => 4, 'name' => 'TELIRE']);
        Distrito::updateOrCreate(['distrito_id' => 70501, 'canton_id' => 705, 'tax_id' => 1, 'name' => 'MATINA']);
        Distrito::updateOrCreate(['distrito_id' => 70502, 'canton_id' => 705, 'tax_id' => 2, 'name' => 'BATAAN']);
        Distrito::updateOrCreate(['distrito_id' => 70503, 'canton_id' => 705, 'tax_id' => 3, 'name' => 'CARANDI']);
        Distrito::updateOrCreate(['distrito_id' => 70601, 'canton_id' => 706, 'tax_id' => 1, 'name' => 'GUACIMO']);
        Distrito::updateOrCreate(['distrito_id' => 70602, 'canton_id' => 706, 'tax_id' => 2, 'name' => 'MERCEDES']);
        Distrito::updateOrCreate(['distrito_id' => 70603, 'canton_id' => 706, 'tax_id' => 3, 'name' => 'POCORA']);
        Distrito::updateOrCreate(['distrito_id' => 70604, 'canton_id' => 706, 'tax_id' => 4, 'name' => 'RIO JIMENEZ']);
        Distrito::updateOrCreate(['distrito_id' => 70605, 'canton_id' => 706, 'tax_id' => 5, 'name' => 'DUCARI']);

    }

}
